version: '3.8'
services:
  database:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=my-username
      - MONGO_INITDB_ROOT_PASSWORD=my-root-password
      - MONGODB_CONNECTION_STRING= mongodb+srv://dbuUser:dbUserPassword@cluster0.lqupv.mongodb.net/devices?retryWrites=true&w=majority
    volumes:
      - ./my_data:/data/db
  device.manager.Services:
    environment:
      - PORT=5001
    #      - RABBIT_MQ_CONNECTION=amqp://admin:tr4H7h8t@10.100.210.24:30672
      - RABBIT_MQ_CONNECTION=amqp://admin:admin@10.100.207.121:5672
      - RABBIT_MQ_DEVICE_QUEUE=DEVICE_QUEUE
      - RABBIT_MQ_TYPE=DEVICE
    build:
      context: './device.Manager.Services'
      dockerfile: './Dockerfile'
    image: device-manager-services:0.1
    depends_on:
      - database
    ports:
      - "5001:5001"
  device.Temperature.Service:
    environment:
      - PORT=6001
      - INTERVAL_MS=1000
      - DEVICE_ID=61407b325bb5b88548b0a7ce
      - DEVICE_API_URL=http://10.100.207.121:5001
        #      - RABBIT_MQ_CONNECTION=amqp://admin:tr4H7h8t@10.100.210.24:30672
      - RABBIT_MQ_CONNECTION=amqp://admin:admin@10.100.207.121:5672
      - RABBIT_MQ_DEVICE_MANAGER_QUEUE=TEMPERATURE_QUEUE
      - SOCKET_EVENT_NAME=TEMPERATURE
    build:
      context: './deviceTemperature.Services'
      dockerfile: './Dockerfile'
    image: device-temperature-services:0.1
    depends_on:
      - database
    ports:
      - "6001:6001"
  socket.device.Service:
    environment:
      - INTERVAL_MS=5000
        #      - RABBIT_MQ_CONNECTION=amqp://admin:tr4H7h8t@10.100.210.24:30672
      - RABBIT_MQ_CONNECTION=amqp://admin:admin@10.100.207.121:5672
      - RABBIT_MQ_QUEUE_NAME=DEVICE_QUEUE
      - SOCKET_EVENT_NAME=DEVICE
      - SOCKET_PORT=1234
    ports:
      - 8081:1234
    build:
      context: './socket.Services'
      dockerfile: './Dockerfile'
    image: socket-device-services:0.1
  socket.temperature.Service:
    environment:
      - INTERVAL_MS=5000
#      - RABBIT_MQ_CONNECTION=amqp://admin:tr4H7h8t@10.100.210.24:30672
      - RABBIT_MQ_CONNECTION=amqp://admin:admin@10.100.207.121:5672
      - RABBIT_MQ_QUEUE_NAME=TEMPERATURE_QUEUE
      - SOCKET_EVENT_NAME=TEMPERATURE
      - SOCKET_PORT=1234
    ports:
      - 8080:1234
    build:
      context: './socket.Services'
      dockerfile: './Dockerfile'
    image: socket-temperature-services:0.1
  thermostat.client:
    build:
      context: './thermostat.client'
      dockerfile: './Dockerfile'
    volumes:
      - ./thermostat.client/config-docker.js:/usr/share/nginx/html/config.js
    image: thermostat.client:0.1
    ports:
    - 3000:80