version: '3.8'
services:
  database:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 7017:27017
#    volumes:
#      - db:/data/db
    networks:
      - thermostat_nodejs
    #    expose:
#      - 27017
  rabbitmqservice:
    image: rabbitmq:3-management
#    environment:
#      - RABBITMQ_DEFAULT_USER=myuser
#      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      - 5672:5672
      - 15672:15672
#    volumes:
#      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
#      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - thermostat_nodejs
volumes:
  db:
networks:
  thermostat_nodejs:
    driver: bridge