window.REACT_APP_DEVICE_API_BASE_URL="http://localhost:5001/api/";
window.REACT_APP_SOCKET_DEVICE_URL="ws:/localhost:8081"
window.REACT_APP_SOCKET_TEMPERATURE_URL="ws://localhost:8080"
window.REACT_APP_SOCKET_TEMPERATURE_EVENT_NAME="TEMPERATURE";
window.REACT_APP_SOCKET_DEVICE_EVENT_NAME="DEVICE";
